Check if platex exists

diff --git a/autolatex b/autolatex
--- a/autolatex
+++ b/autolatex
@@ -2,11 +2,17 @@
 # Filename: autolatex
 # Author: itchyny
 # License: MIT License
-# Last Change: 2014/08/22 14:05:54.
+# Last Change: 2014/10/28 10:30:20.
 
 # Usage: autolatex test.tex
 if [ $# -ne 1 ]; then
   echo 'no argument'
+  exit 1
+fi
+
+# Check if platex exists
+if ! command -v platex > /dev/null 2>&1; then
+  echo 'platex required'
   exit 1
 fi
 
